import 'package:track_my_crypto/crypto.dart';

class CryptoList {
  List<Crypto> cryptoList = [
    Crypto('assets/images/ethereum.png','Ethereum', '(ETH)'),
    Crypto('assets/images/litecoin.png','Litecoin', '(LTC)'),
    Crypto('assets/images/cardano.png','Cardano', '(ADA)'),
    Crypto('assets/images/polkadot.png','Polkadot', '(DOT)'),
    Crypto('assets/images/bitcoincash.png','Bitcoin Cash', '(BCH)'),
    Crypto('assets/images/stellar.png','Stellar', '(XLM)'),
    Crypto('assets/images/dogecoin.png','Dogecoin', '(DOGE)'),
    Crypto('assets/images/binance.png','Binance Coin', '(BNB)'),
    Crypto('assets/images/tether.png','Tether', '(USDT)'),
    Crypto('assets/images/monero.png','Monero', '(XMR)'),
    Crypto('assets/images/xrp.png','Xrp', '(XRP)'),
    Crypto('assets/images/bitcoin.png','Bitcoin', '(BTC)'),
    Crypto('assets/images/usdcoin.png','USD Coin', '(USDC)'),
    Crypto('assets/images/solana.png','Solana', '(SOL)'),
    Crypto('assets/images/avalanche.png','Avalanche', '(AVAX)'),
    Crypto('assets/images/terra.png','Terra', '(LUNA)'),
    Crypto('assets/images/binanceusd.png','Binance USD', '(BUSD)'),
    Crypto('assets/images/shibainu.png','Shiba Inu', '(SHIB)'),
    Crypto('assets/images/polygon.png','Polygon', '(MATIC)'),
    Crypto('assets/images/terrausd.png','Terra USD', '(UST)'),
    Crypto('assets/images/crypto.comcoin.png','Crypto.com Coin', '(CRO)'),
    Crypto('assets/images/wrappedbitcoin.png','Wrapped Bitcoin', '(WBTC)'),
    Crypto('assets/images/dai.png','Dai', '(DAI)'),
    Crypto('assets/images/cosmos.png','Cosmos', '(ATOM)'),
    Crypto('assets/images/chainlink.png','Chain Link', '(LINK)'),
    Crypto('assets/images/nearprotocol.png','NEAR Protocol', '(NEAR)'),
    Crypto('assets/images/uniswap.png','Uniswap', '(UNI)'),
    Crypto('assets/images/tron.png','Tron', '(TRX)'),
    Crypto('assets/images/ftx.png','Ftx Token', '(FTT)'),
    Crypto('assets/images/algorand.png','Algorand', '(ALGO)'),
    Crypto('assets/images/decentraland.png','Decentraland', '(MANA)'),
  ];
}
